---
deployment:
      tasks:
        - export DEPLOYPATH=/home/fitcoach/public_html  # Add /<app_folder> if required
        - /bin/cp fitcoach $DEPLOYPATH                 #Copy specific file to destination from root
        - /bin/cp /home/fitcoach $DEPLOYPATH   #copy specific file from source sub folder
        - /bin cp * $DEPLOYPATH                           #copy all from root 
        - /bin cp /home/* $DEPLOYPATH             #copy all from sub folder root
        - /bin/cp -r * $DEPLOYPATH                        #copy all recursively to $DEPLOYPATH
        
        
